version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - backend_data:/app/database
    restart: always
    networks:
      - app_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:3001/api
    depends_on:
      - backend
    restart: always
    networks:
      - app_network

volumes:
  backend_data:

networks:
  app_network:
    driver: bridge
