version: '3.8' # Versão do Docker Compose

services:
  frontend:
    build:
      context: . # Onde o Dockerfile do frontend está (raiz do projeto)
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Mapeia a porta 3000 do host para a porta 3000 do container
    environment:
      # A URL da API do backend, usando o nome do serviço Docker 'backend'
      NEXT_PUBLIC_API_URL: http://backend:3001/api
    depends_on:
      - backend # Garante que o backend inicie antes do frontend
    volumes:
      - .:/app # Monta o diretório atual do host no /app do container (para desenvolvimento)
      - /app/node_modules # Exclui node_modules da montagem para usar os do container
    restart: unless-stopped

  backend:
    build:
      context: ./backend # Onde o Dockerfile do backend está
      dockerfile: Dockerfile
    ports:
      - "3001:3001" # Mapeia a porta 3001 do host para a porta 3001 do container
    volumes:
      - ./backend:/app # Monta o diretório backend do host no /app do container
      - /app/node_modules # Exclui node_modules da montagem
      - backend_data:/app/database # Volume persistente para o banco de dados SQLite
    restart: unless-stopped
    command: sh -c "npm run init-db && npm start" # Inicializa o DB e depois inicia o servidor

volumes:
  backend_data: # Define o volume nomeado para persistir os dados do backend
