version: '3.8'

services:
  backend:
    build:
      context: ./backend # O Dockerfile do backend está na pasta 'backend'
      dockerfile: Dockerfile
    ports:
      - "3001:3001" # Mapeia a porta 3001 do host para a porta 3001 do contêiner
    volumes:
      # Persiste o arquivo do banco de dados SQLite.
      # 'backend_data' é o nome do volume Docker, '/app/database' é o caminho dentro do contêiner.
      - backend_data:/app/database
    restart: always # Garante que o contêiner do backend sempre reinicie se parar
    networks:
      - app_network # Conecta ao contêiner do frontend na mesma rede

  frontend:
    build:
      context: . # O Dockerfile do frontend está na raiz do projeto
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Mapeia a porta 3000 do host para a porta 3000 do contêiner
    environment:
      # Define a URL da API para o frontend. 'backend' é o nome do serviço do backend no Docker Compose.
      NEXT_PUBLIC_API_URL: http://backend:3001/api
    depends_on:
      - backend # Garante que o backend seja iniciado antes do frontend
    restart: always # Garante que o contêiner do frontend sempre reinicie se parar
    networks:
      - app_network # Conecta ao contêiner do backend na mesma rede

volumes:
  backend_data: # Declara o volume nomeado para persistência do banco de dados

networks:
  app_network:
    driver: bridge # Define uma rede bridge para os contêineres se comunicarem
